### ISSUE TITLE
Can't display Land Cover CCI 

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#302]
### Expected behavior

No tile size error.

### Actual behavior

Tile size error!

See [image.py](https://github.com/CCI-Tools/cate-core/blob/4c58e9425ecb3a127240beb3a804d8acee7b56cf/cate/util/im/image.py#L659-L662)

### Steps to reproduce the problem

1. Open Land Cover CCI (NetCDF)
2. Display image layer

### Specifications 

0.9.0

**Comment by mzuehlke** [comment]
The tile size error has been fixed. The actual display is still very slow. A pyramid generation needs to take place for such large products (at the moment only lc-cci).

**Comment by barsten** [comment]
Hi, I still can't open the LC data from the GUI by pressing the "open" button. I get the error message below. If I use the "read_netcdf" operation, however, it works - somehow. The display looks displayed, i.e. the land cover does not match the continents of the the background map.

Here is the error message that I get when using hte download button of the GUI:
Cate Desktop, version 0.9.0-dev.6

set_workspace_resource() call raised exception: "math domain error"

An error (code 20) occurred while executing a backend process:

Traceback (most recent call last):
  File "C:\Users\carsten\cate\lib\site-packages\cate\util\web\jsonrpchandler.py", line 190, in send_service_method_result
    result = future.result()
  File "C:\Users\carsten\cate\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\carsten\cate\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\carsten\cate\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\carsten\cate\lib\site-packages\cate\util\web\jsonrpchandler.py", line 267, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\carsten\cate\lib\site-packages\cate\webapi\websocket.py", line 303, in set_workspace_resource
    monitor=monitor)
  File "C:\Users\carsten\cate\lib\site-packages\cate\core\wsmanag.py", line 313, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "C:\Users\carsten\cate\lib\site-packages\cate\core\workspace.py", line 598, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\carsten\cate\lib\site-packages\cate\core\workflow.py", line 624, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "C:\Users\carsten\cate\lib\site-packages\cate\core\workflow.py", line 315, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\carsten\cate\lib\site-packages\cate\core\workflow.py", line 977, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "C:\Users\carsten\cate\lib\site-packages\cate\core\op.py", line 211, in __call__
    return_value = self._wrapped_op(**input_values)
  File "C:\Users\carsten\cate\lib\site-packages\cate\ops\io.py", line 63, in open_dataset
    var_names=var_names, region=region)
  File "C:\Users\carsten\cate\lib\site-packages\cate\core\ds.py", line 546, in open_dataset
    return data_source.open_dataset(time_range, region, var_names)
  File "C:\Users\carsten\cate\lib\site-packages\cate\ds\local.py", line 162, in open_dataset
    ds = open_xarray_dataset(paths)
  File "C:\Users\carsten\cate\lib\site-packages\cate\core\ds.py", line 599, in open_xarray_dataset
    n_chunks = ceil(sqrt(temp_ds.nbytes / threshold)) ** 2
ValueError: math domain error

**Comment by forman** [comment]
Closing this because we now have #356, #361, #364
